import assert from "node:assert/strict";
import { readdir, readFile, stat } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", String(process.pid) + "-" + String(Date.now()));
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("server-renders the finished mathematics museum", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>数学美学展 · Math Beauty Museum<\/title>/i);
  assert.match(html, /自然数学馆/);
  assert.match(html, /切换数学展厅/);
  assert.match(html, /数学美学展序厅/);
  assert.match(html, /下一个展厅：自然数学馆/);
  assert.doesNotMatch(html, /THE LANGUAGE BEHIND BEAUTY · PROLOGUE/);
  assert.match(html, /数学探索花园/);
  assert.match(html, /互动工坊/);
  assert.match(html, /我的家乡数学馆/);
  assert.doesNotMatch(html, /journey-intro|class="exhibit|互动实验台/);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape|Building your site/i);
});

test("ships four interactive WebGL halls and twelve concepts", async () => {
  const [museum, garden, workshop, spaceSlice, sliceGeometry, observer, observerEvents, observerPolicy, observerDecide, observerSpeech, page, layout, css, audio, viewport, mascotAsset] = await Promise.all([
    readFile(new URL("../app/NatureMuseum3D.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/MathGarden3D.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/InteractiveWorkshop.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/SpaceSliceLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/space-slice/geometry.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/MathObserver.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/math-observer-events.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/math-observer-policy.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/observer/decide/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/observer/speech/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/audio.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/viewport.ts", import.meta.url), "utf8"),
    readFile(new URL("../public/math-observer-xiaoguan.png", import.meta.url)),
  ]);

  for (const hall of ["自然数学馆", "建筑数学馆", "声音数学馆", "宇宙数学馆"]) {
    assert.match(museum, new RegExp('name: "' + hall + '"'));
  }
  for (const id of [
    "golden", "fractal", "phyllotaxis",
    "pythagoras", "catenary", "tessellation",
    "sine", "harmonics", "chladni",
    "orbit", "galaxy", "resonance",
  ]) {
    assert.match(museum, new RegExp('id: "' + id + '"'));
  }

  assert.equal((museum.match(/key: "(nature|architecture|sound|cosmos)"/g) ?? []).length, 4);
  assert.match(museum, /new THREE\.WebGLRenderer/);
  assert.equal((museum.match(/new THREE\.WebGLRenderer/g) ?? []).length, 2);
  assert.match(museum, /window\.matchMedia\("\(pointer: coarse\)"\)/);
  assert.match(museum, /tapTolerance = event\.pointerType === "touch" \? 18 : 7/);
  assert.match(museum, /webglcontextlost/);
  assert.match(museum, /setRetryKey\(\(key\) => key \+ 1\)/);
  assert.match(museum, /container\.dataset\.webglError = "true"/);
  assert.match(museum, /className="webgl-fallback-actions"/);
  assert.match(museum, /进入自然数学馆/);
  assert.match(museum, /className="museum-keyboard-exhibits"/);
  assert.match(museum, /键盘访问/);
  assert.match(museum, /OrbitControls/);
  assert.match(museum, /switchHall\(-1\)/);
  assert.match(museum, /switchHall\(1\)/);
  assert.match(museum, /const handleHallWheel/);
  assert.match(museum, /wheelAccumulator\.current \+= delta/);
  assert.match(museum, /wheelAccumulator\.current > 0 \? -1 : 1/);
  assert.match(museum, /const handleMuseumWheel/);
  assert.match(museum, /bounds\.bottom <= 0 \|\| bounds\.top >= window\.innerHeight/);
  assert.match(museum, /window\.addEventListener\("wheel", handleMuseumWheel, \{ passive: false \}\)/);
  assert.match(museum, /window\.removeEventListener\("wheel", handleMuseumWheel\)/);
  assert.match(museum, /ref=\{galleryRef\}/);
  assert.doesNotMatch(museum, /onWheel=\{handleHallWheel\}/);
  assert.match(museum, /direction > 0 && hallIndex >= HALLS\.length - 1\) return/);
  assert.doesNotMatch(museum, /getElementById\("garden"\)\?\.scrollIntoView/);
  assert.match(museum, /已经位于最后一个展厅/);
  assert.match(museum, /museum-navigation-busy/);
  assert.match(museum, /MUSEUM_CAMERA_STOPS/);
  assert.match(museum, /new THREE\.Vector3\(0, 4\.8, 18\.8\)/);
  assert.match(museum, /controls\.enableZoom = false/);
  assert.match(museum, /HALL_CENTERS/);
  assert.doesNotMatch(museum, /new THREE\.CatmullRomCurve3/);
  assert.match(museum, /class PortalArchCurve extends THREE\.Curve<THREE\.Vector3>/);
  assert.match(museum, /const arcLength = Math\.PI \* radius/);
  assert.match(museum, /new THREE\.TubeGeometry\(curve, 96, \.045 \+ layer \* \.014, 12, false\)/);
  assert.match(museum, /glowMaterial\(color, \(\.58 - layer \* \.11\) \* opacityScale\)/);
  assert.match(museum, /addTextRing/);
  assert.match(museum, /let cursor = offset - phraseArc \/ 2/);
  assert.doesNotMatch(museum, /repeatCount|repeatGap/);
  assert.match(museum, /new THREE\.CylinderGeometry\(radius, radius, bandHeight/);
  assert.match(museum, /transmission: \.78/);
  assert.match(museum, /"MATH BEAUTY MUSEUM", 5\.45, 8\.55, "#f4f2ff", \.96, 0, 2\.36/);
  assert.match(museum, /"数学美学展", 3\.7, 7\.65, "#b8c9ff", 1\.08, 0, 1\.52/);
  assert.match(museum, /emissiveMap: texture/);
  assert.match(museum, /emissiveIntensity: 2\.2/);
  assert.doesNotMatch(museum, /atrium\.rotation\.y = elapsed/);
  assert.match(museum, /museumAction = "enter-first-hall"/);
  assert.match(museum, /function makeChevronMaterial/);
  assert.match(museum, /ctx\.lineCap = "round"/);
  assert.match(museum, /entranceGuide\.position\.set\(0, -\.72, 5\.45\)/);
  assert.match(museum, /new THREE\.PlaneGeometry\(\.9, \.9\), makeChevronMaterial/);
  assert.doesNotMatch(museum, /点击进入 {2}· {2}ENTER/);
  assert.doesNotMatch(museum, /const arrowShape = new THREE\.Shape/);
  assert.doesNotMatch(museum, /const guidePoints =/);
  assert.doesNotMatch(museum, /const guideCurve =/);
  assert.match(museum, /onEnterRef\.current\(\)/);
  assert.doesNotMatch(museum, /点击地面指引进入第一展馆/);
  assert.match(museum, /MATH BEAUTY MUSEUM/);
  assert.match(museum, /数学美学展/);
  assert.doesNotMatch(museum, /new THREE\.TorusKnotGeometry/);
  assert.match(museum, /makeSquareRootSurfaceGeometry\(lowPower \? 18 : 30, lowPower \? 56 : 104\)/);
  assert.match(museum, /function roundedRectPath/);
  assert.match(museum, /const secondaryColor: Record<HallKey, string>/);
  assert.match(museum, /FORM · NUMBER · PATTERN/);
  assert.match(museum, /opacity: \.88/);
  assert.match(museum, /polygonOffsetFactor: -1/);
  assert.match(museum, /face\.position\.z = \.132/);
  assert.match(museum, /face\.renderOrder = 1/);
  assert.doesNotMatch(museum, /const pedestal = new THREE\.Mesh/);
  assert.match(museum, /const atriumBlue = "#5d7fd0"/);
  assert.match(museum, /const atriumPortalMaterial = physical\(atriumBlue/);
  assert.doesNotMatch(museum, /addAtriumDepthCorridor|atrium-depth-corridor/);
  assert.match(museum, /import \{ Reflector \} from "three\/examples\/jsm\/objects\/Reflector\.js"/);
  assert.match(museum, /new Reflector\(new THREE\.PlaneGeometry\(34, 108\)/);
  assert.match(museum, /const reflectionMaxResolution = \(navigator\.hardwareConcurrency \?\? 8\) >= 10 \? 1536 : 1024/);
  assert.match(museum, /textureWidth: reflectionResolution/);
  assert.match(museum, /multisample: 2/);
  assert.match(museum, /reflectionTarget\.setSize\(targetResolution, targetResolution\)/);
  assert.match(museum, /name: "MutedAtriumReflector"/);
  assert.match(museum, /vec3 desaturated = mix\(vec3\(luminance\), reflected, 0\.26\)/);
  assert.match(museum, /vec3 softened = mix\(desaturated, color, 0\.58\) \* 0\.58/);
  assert.match(museum, /atriumFloor\.name = "atrium-reflective-floor"/);
  assert.match(museum, /atriumFloor\.position\.set\(0, -1\.18, -36\)/);
  assert.match(museum, /atriumFloor\.visible = atriumIsActive/);
  assert.match(museum, /const ceilingPointCount = lowPower \? 34 : 86/);
  assert.match(museum, /atriumCeilingParticles\.name = "atrium-ceiling-particles"/);
  assert.match(museum, /makePointCloud\(ceilingPoints, "#c5d7ff", lowPower \? \.055 : \.072, \.68\)/);
  assert.match(museum, /makePointCloud\(ceilingPoints, "#5f89ee", lowPower \? \.12 : \.18, \.14\)/);
  assert.match(museum, /atriumCeilingGlow\.name = "atrium-ceiling-glow"/);
  assert.match(museum, /atriumCeilingParticles\.visible = atriumIsActive/);
  assert.match(museum, /atriumCeilingGlow\.visible = atriumIsActive/);
  assert.match(museum, /atriumPortals\.name = "atrium-four-hall-portals"/);
  assert.match(museum, /const portalRoute = \[new THREE\.Vector3\(0, 0, 0\), \.\.\.HALL_CENTERS\]/);
  assert.match(museum, /HALLS\.forEach\(\(hall, index\) =>/);
  assert.match(museum, /previous\.clone\(\)\.lerp\(next, \.68\)/);
  assert.match(museum, /hall\.key === "nature" \? \.42 : \.58/);
  assert.match(museum, /portal\.scale\.setScalar\(\.74\)/);
  assert.match(museum, /atriumPortals\.visible = atriumIsActive/);
  assert.match(museum, /floor\.visible = !atriumIsActive/);
  assert.match(museum, /opacity: lowPower \? \.28 : \.34/);
  assert.match(museum, /emissiveIntensity: \.28/);
  assert.match(museum, /continuum\.position\.set\(0, 3\.05, \.25\)/);
  assert.match(museum, /function makeSquareRootSurfaceGeometry\(radialSegments: number, angularSegments: number\)/);
  assert.match(museum, /const theta = angleIndex \/ angularSegments \* Math\.PI \* 4/);
  assert.match(museum, /Math\.sqrt\(radius\) \* Math\.cos\(theta \* \.5\) \* 1\.58/);
  assert.match(museum, /geometry\.setAttribute\("aBranchAngle"/);
  assert.match(museum, /const surfaceParameters = \{/);
  assert.match(museum, /roughness: \.76/);
  assert.match(museum, /transmission: \.08/);
  assert.match(museum, /opacity: \.82/);
  assert.match(museum, /color: "#93b8ff", wireframe: true/);
  assert.match(museum, /material\.customProgramCacheKey = \(\) => "atrium-square-root-surface-v1"/);
  assert.match(museum, /float livingAngle = aBranchAngle \+ uSurfaceTwist/);
  assert.match(museum, /surfaceParameters\.time\.value = elapsed \* 1\.9/);
  assert.match(museum, /surfaceParameters\.opening\.value = 1 \+ Math\.sin\(elapsed \* \.88\) \* \.25/);
  assert.match(museum, /surfaceParameters\.twist\.value = Math\.sin\(elapsed \* \.63 \+ \.7\) \* \.62/);
  assert.match(museum, /surfaceParameters\.shear\.value = Math\.sin\(elapsed \* \.47 \+ 1\.6\) \* \.12/);
  assert.match(museum, /surfaceParameters\.lift\.value = Math\.cos\(elapsed \* \.71 \+ \.2\) \* \.1/);
  assert.match(museum, /transformed\.x \+= transformed\.y \* uSurfaceShear/);
  assert.match(museum, /surface\.position\.y = Math\.sin\(elapsed \* \.56\) \* \.16/);
  assert.match(museum, /surface\.rotation\.set\(-\.18 \+ Math\.sin/);
  assert.match(museum, /function makeTesseractProjection\(\)/);
  assert.match(museum, /vertex \^ \(1 << dimension\)/);
  assert.match(museum, /const faces: Array<\[number, number, number, number\]> = \[\]/);
  assert.match(museum, /new THREE\.CylinderGeometry\(\.035, \.035, 1, 8/);
  assert.match(museum, /new THREE\.InstancedMesh\(edgeGeometry, edgeMaterial, edges\.length\)/);
  assert.match(museum, /opacity: \.065, side: THREE\.DoubleSide/);
  assert.match(museum, /function updateTesseractProjection\(group: THREE\.Group, elapsed: number\)/);
  assert.match(museum, /\[x, w\] = rotate\(x, w, elapsed \* \.72\)/);
  assert.match(museum, /const projectionDistance = 3\.65 \+ Math\.sin\(elapsed \* \.38\) \* \.34/);
  assert.match(museum, /const perspective = projectionScale \/ \(projectionDistance - w\)/);
  assert.match(museum, /edgeMesh\.setMatrixAt\(edgeIndex, edgeTransform\.matrix\)/);
  assert.match(museum, /facePositions\[targetOffset\] = projected\[sourceOffset\]/);
  assert.match(museum, /const tesseractPulse = \.95 \+ Math\.sin\(elapsed \* \.67 \+ \.4\) \* \.09/);
  assert.match(museum, /function makeFormulaHologram\(formula: string, color: string, lowPower: boolean\)/);
  assert.match(museum, /"w² = z {2}· {2}w = ±√z"/);
  assert.match(museum, /"\(x, y, z, w\) {2}→ {2}\(X, Y, Z\)"/);
  assert.match(museum, /squareRootFormula\.visible = loadedHallIndex < 0 && showSquareRootSurface/);
  assert.match(museum, /tesseract\.visible = loadedHallIndex < 0 && !showSquareRootSurface/);
  assert.match(museum, /className="atrium-artwork-carousel"/);
  assert.match(museum, /\["复平方根曲面", "四维超立方体"\]/);
  assert.match(museum, /const displayRing = new THREE\.Mesh/);
  assert.match(museum, /new THREE\.TorusGeometry\(2\.72, \.045/);
  assert.match(museum, /displayRing\.position\.y = -4\.2/);
  assert.match(museum, /const beamRig = new THREE\.Group/);
  assert.match(museum, /const outerBeam = new THREE\.Mesh/);
  assert.match(museum, /new THREE\.CylinderGeometry\(2\.62, 2\.9, beamHeight/);
  assert.doesNotMatch(museum, /const sourceRing = new THREE\.Mesh/);
  assert.match(museum, /const floorLightPool = new THREE\.Mesh/);
  assert.match(museum, /const beamSpot = new THREE\.SpotLight/);
  assert.match(museum, /const beamDustCount = lowPower \? 34 : 84/);
  assert.match(museum, /color: "#3977e8"/);
  assert.match(museum, /makePointCloud\(beamDustPoints, "#78a6ff"/);
  assert.match(museum, /beamMaterial\(lowPower \? \.045 : \.072\)/);
  assert.match(museum, /if \(atriumFloor instanceof Reflector\) atriumFloor\.dispose\(\)/);
  assert.doesNotMatch(museum, /className="nature-museum-title atrium-title"/);
  assert.doesNotMatch(museum, /THE LANGUAGE BEHIND BEAUTY · PROLOGUE/);
  assert.doesNotMatch(museum, /continuumStates|continuumDust|pedestalHalo/);
  assert.doesNotMatch(museum, /new THREE\.IcosahedronGeometry\(2\.15/);
  assert.match(museum, /makePointCloud/);
  assert.match(museum, /function addHallHologram/);
  assert.match(museum, /group\.scale\.setScalar\(\.8\)/);
  assert.match(museum, /function buildHallScene/);
  assert.match(museum, /hallTitle\.position\.set\(center\.x, 7\.78, center\.z - 5\.62\)/);
  assert.match(museum, /titleFace\.position\.z = \.08/);
  assert.match(museum, /\[-\.005, -\.07\]\.forEach/);
  assert.match(museum, /titleDepthMaterial\.emissiveIntensity = \.68/);
  assert.match(museum, /let activeHallScene: HallSceneBundle \| null = null/);
  assert.match(museum, /disposeObject\(activeHallScene\.root\)/);
  assert.match(museum, /loadOnlyHall\(requestedHallIndex\)/);
  assert.match(museum, /container\.dataset\.loadedHall/);
  assert.match(museum, /container\.dataset\.targetFps = lowPower \? "30" : "60"/);
  assert.match(museum, /const minimumFrameInterval = lowPower \? 1000 \/ 30 : 0/);
  assert.match(museum, /if \(loadedHallIndex < 0\)/);
  assert.match(museum, /\["fibonacci", "architecture", "fourier", "galaxy"\]/);
  assert.match(museum, /new THREE\.SphereGeometry\(1\.78/);
  assert.match(museum, /transmission: lowPower \? \.18 : \.72/);
  assert.match(museum, /particles\.userData\.waveSamples/);
  assert.match(museum, /positions\.needsUpdate = true/);
  assert.doesNotMatch(museum, /addHallSignature/);
  assert.match(museum, /transmission:/);
  assert.match(museum, /type="range"/);
  assert.equal((museum.match(/symbol: "/g) ?? []).length, 37);
  assert.match(museum, /key: "spiralScale", symbol: "a"/);
  assert.match(museum, /AUTO_CONTROL_KEYS/);
  assert.match(museum, /className="nature-lab-live-vars"/);
  assert.match(museum, /aria-label="公式实时变量"/);
  assert.match(museum, /controlDisplayValue/);
  assert.match(museum, /activeControlKey/);
  assert.match(museum, /isAutoPlaying/);
  assert.match(museum, /自动演示/);
  assert.match(museum, /暂停动画/);
  assert.match(museum, /requestAnimationFrame\(animateControls\)/);
  assert.match(museum, /hall-transition-/);
  assert.match(museum, /THREE\.PCFSoftShadowMap/);
  assert.match(museum, /function SoundDrivePanel/);
  assert.match(museum, /function Galaxy3DPreview/);
  assert.match(museum, /可拖动旋转与缩放的三维螺旋星系/);
  assert.match(museum, /selected\.id === "galaxy"/);
  assert.match(museum, /mobileCanvas \? 1\.5 : 2\.5/);
  assert.match(museum, /lowPower \? 1\.25 : 2/);
  assert.match(garden, /controls\.autoRotate=!reducedMotion/);
  assert.match(garden, /renderer\.shadowMap\.enabled=!lowPower/);
  assert.match(garden, /tapTolerance=e\.pointerType==="touch"\?18:7/);
  assert.match(garden, /webglcontextlost/);
  assert.match(garden, /setRetryKey\(key=>key\+1\)/);
  assert.match(garden, /container\.dataset\.webglError="true"/);
  assert.match(garden, /container\.dataset\.quality=lowPower\?"eco":"standard"/);
  assert.match(garden, /new THREE\.CircleGeometry\(30,lowPower\?64:128\)/);
  assert.match(garden, /const seedGeometry=new THREE\.SphereGeometry\(\.028,10,8\)/);
  assert.match(garden, /const branchMaterials=/);
  assert.match(garden, /const geometries=new Set<THREE\.BufferGeometry>/);
  assert.match(garden, /gardenCanvasReady/);
  assert.match(garden, /intersectionRatio>=\.01/);
  assert.match(garden, /stopObservingVisibility\(\)/);
  assert.match(museum, /document\.body\.classList\.contains\("exhibit-mode"\)/);
  assert.match(museum, /<select/);
  assert.match(museum, /className="sound-clip-select"/);
  assert.doesNotMatch(museum, /className="sound-clip-grid"/);
  assert.match(museum, /navigator\.mediaDevices\.getUserMedia/);
  assert.match(museum, /createCompatibleAudioContext\(\)/);
  assert.match(museum, /document\.addEventListener\("visibilitychange", pauseWhenHidden\)/);
  assert.match(garden, /const POND_TRACKS/);
  assert.match(garden, /莫扎特钢琴协奏曲/);
  assert.match(garden, /致爱丽丝/);
  assert.match(garden, /G 大调小步舞曲/);
  assert.match(garden, /aria-label="选择喷泉音乐"/);
  assert.match(garden, /resumeAudioContext\(context\)/);
  assert.match(garden, /if\(document\.hidden\)stopPondSound\(\)/);
  assert.match(garden, /audio\.playbackRate=1/);
  assert.match(garden, /source\.connect\(analyser\);analyser\.connect\(context\.destination\)/);
  assert.doesNotMatch(garden, /pondStepTimer|setInterval\(advance,track\.tempo\)/);
  assert.match(audio, /webkitAudioContext/);
  assert.match(audio, /context\.state !== "running"/);
  assert.match(museum, /observeElementSize\(container, resize\)/);
  assert.match(museum, /observeElementSize\(canvas, resize\)/);
  assert.match(viewport, /"ResizeObserver" in window/);
  assert.match(viewport, /orientationchange/);
  assert.match(viewport, /window\.visualViewport\?\.addEventListener\("resize"/);
  assert.match(viewport, /if \(!\("IntersectionObserver" in window\)\)/);
  assert.match(museum, /context\.createAnalyser\(\)/);
  assert.match(museum, /id: "birdsong"/);
  assert.match(museum, /id: "stream"/);
  assert.match(museum, /id: "humming"/);
  assert.match(museum, /鸟鸣清晨/);
  assert.match(museum, /溪流叮咚/);
  assert.match(museum, /柔和哼鸣旋律/);
  assert.match(museum, /source: "\/audio\/birdsong-morning\.mp3"/);
  assert.match(museum, /source: "\/audio\/flowing-stream\.mp3"/);
  assert.match(museum, /id: "crystal"/);
  assert.match(museum, /id: "pulse"/);
  assert.match(museum, /id: "cosmos"/);
  assert.match(museum, /signalRef\.current/);
  assert.match(museum, /const left = \(width - size\) \/ 2/);
  assert.match(museum, /const top = \(height - size\) \/ 2/);
  assert.match(museum, /const edgeInset = size \* \.045/);
  assert.doesNotMatch(museum, /ctx\.strokeStyle = "#b9c4d6"/);
  assert.doesNotMatch(museum, /body\.style\.position = "fixed"/);
  assert.match(museum, /galleryRef\.current\?\.scrollIntoView/);
  assert.match(museum, /body\.classList\.add\("exhibit-mode"\)/);
  assert.doesNotMatch(museum, /event\.clientY <= 12/);
  assert.doesNotMatch(museum, /updateGlobalNavigation/);
  assert.match(museum, /body\.classList\.remove\("exhibit-mode", "exhibit-nav-visible"\)/);
  assert.match(museum, /root\.style\.overscrollBehavior = "none"/);
  assert.match(museum, /onWheel=\{\(event\) => event\.stopPropagation\(\)\}/);
  assert.match(museum, /className="immersive-lab-header"/);
  assert.match(museum, /nature-console-grid/);
  assert.doesNotMatch(museum, /className="nature-preview-caption"/);
  assert.doesNotMatch(museum, /ctx\.fillText\(item\.previewCaption/);
  assert.match(museum, /className="nature-console-story"/);
  assert.match(museum, /className="nature-lab-reward"/);
  assert.match(museum, /已对准|试着对准它/);
  assert.doesNotMatch(museum, /className="nature-room-dock"/);
  assert.match(css, /\.museum-hall-arrows/);
  assert.match(css, /\.museum-route-indicator/);
  assert.match(css, /\.museum-route-indicator\{[^}]*padding:8px 0;border:0;background:transparent;box-shadow:none/);
  assert.match(css, /\.atrium-artwork-carousel\{[^}]*bottom:104px/);
  assert.match(css, /\.garden-guide\{[^}]*top:290px/);
  assert.match(css, /\.immersive-lab-header/);
  assert.match(css, /\.nature-console-grid/);
  assert.match(css, /\.nature-lab-live-vars/);
  assert.match(css, /\.nature-lab-live-vars\{display:flex!important;flex-wrap:wrap/);
  assert.match(css, /color:#a9b0bc;font-size:14px;line-height:1\.2/);
  assert.match(css, /\.nature-lab-live-vars span i\{color:#dbe0e9;font-family:Georgia,serif;font-size:18px/);
  assert.match(css, /\.nature-console-actions/);
  assert.match(css, /\.nature-control-name em/);
  assert.match(css, /nature-formula-expression>strong\{font-size:40px/);
  assert.match(css, /Full-screen exhibit mode and compact fixed console/);
  assert.match(css, /\.exhibit-mode \.site-header/);
  assert.match(css, /\.exhibit-mode \.site-header\{display:none\}/);
  assert.match(css, /\.garden-detail-mode \.site-header\{display:none\}/);
  assert.match(css, /\.certificate-mode \.site-header\{display:none\}/);
  assert.match(css, /\.garden-nav-theme \.site-header\{color:#162b3c\}/);
  assert.match(css, /\.garden-nav-theme \.site-header nav button\{color:#233f52;font-weight:700\}/);
  assert.match(css, /\.garden-nav-theme \.progress-button\{[^}]*background:rgba\(255,255,255,\.58\)/);
  assert.match(css, /\.site-header\{transform:none;opacity:1;pointer-events:auto/);
  assert.doesNotMatch(css, /\.exhibit-mode\.exhibit-nav-visible \.site-header/);
  assert.doesNotMatch(css, /\.exhibit-mode\.exhibit-nav-visible \.nature-lab-close/);
  assert.match(css, /\.site-header\{color:#f3f4fa;background:transparent;border:0;box-shadow:none;backdrop-filter:none\}/);
  assert.match(css, /\.nature-lab-shell\{width:100%;height:100svh/);
  assert.match(css, /\.nature-lab-controls\{position:fixed/);
  assert.match(css, /\.sound-clip-select select/);
  assert.match(css, /\.galaxy-3d-preview/);
  assert.match(css, /safe-area-inset-top/);
  assert.match(css, /height:100dvh/);
  assert.match(css, /Mobile child-friendly readability and cross-browser touch targets/);
  assert.match(css, /\.brand\{min-height:44px\}/);
  assert.match(css, /\.nature-lab-control>span\{font-size:10px\}/);
  assert.match(css, /input\[type=range\]::-moz-range-thumb\{width:20px;height:20px\}/);
  assert.match(css, /data-webgl-ready="false"\] canvas\{opacity:0\}/);
  assert.match(css, /Recoverable WebGL fallback/);
  assert.match(css, /\[data-webgl-error="true"\] \.webgl-retry\{display:inline-flex\}/);
  assert.match(css, /\[data-webgl-error="true"\] \.webgl-fallback-actions\{display:flex\}/);
  assert.match(css, /\.museum-keyboard-exhibits:focus-within/);
  assert.match(css, /\.sound-drive-panel/);
  assert.match(css, /overscroll-behavior:contain/);
  assert.match(css, /\.hall-transition-leaving/);
  assert.doesNotMatch(css, /\.museum-hall-switcher/);
  assert.match(css, /--hall-accent/);
  assert.match(page, />四展馆</);
  const hallNavIndex = page.indexOf(">四展馆</button>");
  const workshopNavIndex = page.indexOf(">互动工坊</button>");
  const gardenNavIndex = page.indexOf(">数学花园</button>");
  const hometownNavIndex = page.indexOf(">我的家乡数学馆</button>");
  assert.ok(hallNavIndex >= 0 && hallNavIndex < workshopNavIndex);
  assert.ok(workshopNavIndex < gardenNavIndex);
  assert.ok(gardenNavIndex < hometownNavIndex);
  assert.match(page, /<LazyNatureMuseumWorld \/>/);
  assert.match(page, /lazy\(async \(\) =>/);
  assert.match(page, /import\("\.\/NatureMuseum3D"\)/);
  assert.match(page, /import\("\.\/MathGarden3D"\)/);
  assert.match(page, /import\("\.\/InteractiveWorkshop"\)/);
  assert.match(page, /<DeferredInteractiveWorkshop \/>/);
  assert.match(page, /<LazyMathObserver \/>/);
  assert.match(page, /observer-garden-first/);
  assert.match(page, /<LazyNatureMuseumWorld \/><\/Suspense>\s*<DeferredInteractiveWorkshop \/>\s*<DeferredMathGarden/);
  assert.match(page, />互动工坊</);
  assert.match(page, /--progress-value/);
  assert.match(workshop, /new THREE\.WebGLRenderer/);
  assert.match(workshop, /new OrbitControls/);
  assert.match(workshop, /className="workshop-gallery-webgl"/);
  assert.match(workshop, /new THREE\.CylinderGeometry/);
  assert.doesNotMatch(workshop, /new THREE\.(CircleGeometry|TorusGeometry)/);
  assert.match(workshop, /const PANEL_RADIUS = \.84/);
  assert.equal((workshop.match(/title: ""/g) ?? []).length, 4);
  assert.match(workshop, /title: "空间切片"/);
  assert.match(workshop, /color: "#368e97", title: "空间切片"/);
  assert.match(workshop, /<SpaceSliceLab close=/);
  assert.match(workshop, /observer-open-slice/);
  assert.match(spaceSlice, /空间切片实验室/);
  assert.match(spaceSlice, /new THREE\.PlaneGeometry/);
  assert.match(spaceSlice, /new THREE\.TorusGeometry/);
  assert.match(spaceSlice, /new THREE\.TorusGeometry\(1\.52, \.018/);
  assert.match(spaceSlice, /new THREE\.TorusGeometry\(1\.52, \.052/);
  assert.match(spaceSlice, /ringHitX\.userData\.axis = "x"/);
  assert.match(spaceSlice, /ringHitY\.userData\.axis = "y"/);
  assert.match(spaceSlice, /raycaster\.ray\.intersectPlane\(drag\.plane/);
  assert.match(spaceSlice, /Math\.atan2\(sine, cosine\)/);
  assert.match(spaceSlice, /orientation\.copy\(drag\.orientation\)\.premultiply\(rotation\)/);
  assert.match(spaceSlice, /ringXActive\.visible = axis === "x"/);
  assert.match(spaceSlice, /style\.cursor = hit\?\.object\.userData\.handle === "move" \? "ns-resize" : hit \? "grab" : "default"/);
  assert.doesNotMatch(spaceSlice, /new THREE\.TubeGeometry/);
  assert.match(spaceSlice, /coneSection \? \(isReveal \? "#6d5abc" : "#9184d4"\)/);
  assert.match(spaceSlice, /opacity: isReveal \? \.55 : \.28/);
  assert.match(spaceSlice, /section-view-\$\{shape\}/);
  assert.match(spaceSlice, /path\.closed \? "closed" : "open"/);
  assert.match(spaceSlice, /role="tablist"/);
  assert.match(spaceSlice, /切开看看/);
  assert.match(spaceSlice, /sessionStorage\.setItem\("space-slice-discoveries"/);
  assert.match(spaceSlice, /slice-first-rotation/);
  assert.match(spaceSlice, /slice-result-\$\{shape\}/);
  assert.match(sliceGeometry, /function intersectTriangle/);
  assert.match(sliceGeometry, /function stitchSegments/);
  assert.match(sliceGeometry, /neighbors\.size === 1/);
  assert.match(sliceGeometry, /type: "parabola"/);
  assert.match(sliceGeometry, /type: "hyperbola"/);
  assert.match(css, /\.section-view-canvas\{width:100%;height:auto;aspect-ratio:1\}/);
  assert.match(css, /\.section-path,\.section-path\.open\{fill:rgba\(18,103,127,\.38\);stroke:none\}/);
  assert.match(css, /\.section-view-cone \.section-path\{fill:rgba\(109,90,188,\.4\)\}/);
  assert.match(css, /input::-webkit-slider-thumb/);
  assert.match(css, /\.space-slice-lab/);
  assert.match(css, /\.math-observer\{position:fixed/);
  assert.match(observer, /SpeechSynthesisUtterance/);
  assert.match(observer, /math-observer-xiaoguan\.png/);
  assert.match(observer, /utterance\.pitch = 1/);
  assert.match(observer, /\/api\/observer\/decide/);
  assert.match(observer, /\/api\/observer\/speech/);
  assert.match(observer, /math-observer-participation/);
  assert.match(observer, /activeInteractionRef/);
  assert.match(observerEvents, /math-observer-cue/);
  assert.match(observerEvents, /math-observer-action/);
  assert.match(observerPolicy, /quiet: \{ threshold: \.84/);
  assert.match(observerPolicy, /balanced: \{ threshold: \.68/);
  assert.match(observerPolicy, /active: \{ threshold: \.53/);
  assert.match(observerDecide, /compatible-mode\/v1\/chat\/completions/);
  assert.match(observerDecide, /action.*silent\|speak/);
  assert.match(observerSpeech, /config\.ttsModel/);
  assert.match(observerSpeech, /multimodal-generation\/generation/);
  assert.match(observerSpeech, /SpeechSynthesizer/);
  assert.match(observerSpeech, /cosyvoice-/);
  assert.match(museum, /observer-hall-\$\{HALLS\[hallIndex\]\.key\}/);
  assert.equal(mascotAsset[25], 6, "math observer mascot must keep a true RGBA alpha channel");
  assert.match(workshop, /new THREE\.TextureLoader\(\)\.load\(`data:image\/svg\+xml/);
  assert.match(workshop, /width="2048" height="2048"/);
  assert.match(workshop, /font-size="128"/);
  assert.match(workshop, /texture\.rotation = Math\.PI \/ 2/);
  assert.match(workshop, /new THREE\.CylinderGeometry\(PANEL_RADIUS, PANEL_RADIUS, \.2, 128, 1, false\)/);
  assert.match(workshop, /\[sideMaterial, faceMaterial, sideMaterial\]/);
  assert.doesNotMatch(workshop, /mountingDisk|bayXs/);
  assert.match(workshop, /THREE\.VSMShadowMap/);
  assert.match(workshop, /THREE\.ACESFilmicToneMapping/);
  assert.match(workshop, /shadowMapSize = window\.innerWidth > 1100/);
  assert.match(workshop, /keyLight\.shadow\.mapSize\.set\(shadowMapSize, shadowMapSize\)/);
  assert.match(workshop, /new THREE\.RectAreaLight/);
  assert.match(workshop, /new THREE\.SpotLight/);
  assert.match(workshop, /globalCompositeOperation = "destination-out"/);
  assert.match(workshop, /activeFlip/);
  assert.match(workshop, /eased \* Math\.PI \* 2/);
  assert.match(workshop, /detailOpenRef\.current && !detailOpen/);
  assert.match(workshop, /returnRequestRef\.current\.version \+ 1/);
  assert.match(workshop, /panelIndex = Math\.max\(0, PANELS\.findIndex/);
  assert.match(workshop, /returnAnimation/);
  assert.match(workshop, /group\.userData\.baseZ = panel\.position\[2\]/);
  assert.match(workshop, /baseZ \+ Math\.sin\(progress \* Math\.PI\) \* \.035/);
  assert.match(workshop, /THREE\.MathUtils\.lerp\(returnAnimation\.fromZ, baseZ, eased\)/);
  assert.doesNotMatch(workshop, /gridMaterial/);
  assert.match(workshop, /title: "剪纸"/);
  assert.match(workshop, /即将开放/);
  assert.match(workshop, /webglcontextlost/);
  assert.match(workshop, /重新开启 3D 展厅/);
  assert.match(workshop, /setPointerCapture/);
  assert.match(workshop, /onLostPointerCapture/);
  assert.match(workshop, /context\.translate\(geometry\.centerX, geometry\.centerY\)/);
  assert.match(workshop, /function carveCuts/);
  assert.match(workshop, /type CutShape = \{ points: CutPoint\[\]; closed: boolean \}/);
  assert.match(workshop, /function polygonArea/);
  assert.match(workshop, /width \* \.62, height \* \.64/);
  assert.match(workshop, /visibleCenterY = height \* \.54/);
  assert.match(workshop, /path\.closePath\(\)/);
  assert.match(workshop, /context\.fill\(mappedCutPath\(shape/);
  assert.match(workshop, /finalRadius, true\), "evenodd"/);
  assert.match(workshop, /globalCompositeOperation = "destination-out"/);
  assert.match(workshop, /getCoalescedEvents/);
  assert.match(workshop, /正在圈选 · 松开完成剪裁/);
  assert.match(workshop, /区域已剪掉 · 可以继续圈选/);
  assert.match(workshop, /松开后剪掉内部/);
  assert.match(workshop, /nextRotation/);
  assert.match(workshop, /Math\.min\(360/);
  assert.match(workshop, /旋转欣赏/);
  assert.match(workshop, /左右拖动/);
  assert.match(workshop, /drawUnfoldedPaper/);
  assert.match(workshop, /\[4, 6, 8, 12\]/);
  assert.match(workshop, /360° ÷/);
  assert.match(workshop, /prefers-reduced-motion: reduce/);
  assert.doesNotMatch(workshop, /旋轮线画笔|对称印花|波形织布机|type="range"/);
  assert.match(css, /\.workshop-world\.workshop-gallery\{height:100svh;min-height:620px;padding:0;overflow:hidden/);
  assert.match(css, /background:#d9dde2/);
  assert.match(css, /\.workshop-paper-entry\{[^}]*grid-template-columns:1fr auto 1fr/);
  assert.match(css, /\.workshop-paper-entry span\{grid-column:2;grid-row:1;color:#747b84;font-size:8px;font-weight:450/);
  assert.match(css, /\.workshop-paper-entry b\{grid-column:2;grid-row:2;font-size:15px\}/);
  assert.match(css, /\.workshop-paper-entry i\{grid-column:3;grid-row:1\/3;justify-self:end/);
  assert.match(css, /\.workshop-nav-theme \.progress-button span\{color:#252a31;background:radial-gradient/);
  assert.match(css, /conic-gradient\(#69717b 0 var\(--progress-value\),#cbd0d6 var\(--progress-value\) 100%\)/);
  assert.match(css, /\.garden-nav-theme \.progress-button span\{color:#173341;background:radial-gradient/);
  assert.match(css, /\.workshop-detail-mode\{overflow:hidden\}/);
  assert.match(css, /\.papercut-canvas-wrap canvas\{[^}]*touch-action:none/);
  assert.match(css, /\/\* Cool-light paper-cutting studio \*\//);
  assert.match(css, /\.papercut-shell\{border-color:rgba\(28,32,38,.14\);background:#e9ecf0;color:#171a20/);
  assert.match(css, /\.papercut-shell>header\{border-right:1px solid rgba\(28,32,38,.1\);background:#f0f2f5\}/);
  assert.match(css, /\.papercut-shell>aside\{border-left-color:rgba\(28,32,38,.11\);background:#e8ebef\}/);
  assert.match(css, /\/\* Paper scale, hierarchy and unfolded rotation \*\//);
  assert.match(css, /\.papercut-draw-hint\{top:92px/);
  assert.match(css, /\.papercut-shell>aside>\.papercut-repeat-options b\{font:800 36px\/1/);
  assert.match(css, /\.papercut-shell>aside>span\{color:#20242a;font-weight:760\}/);
  assert.match(css, /\.papercut-shell>aside>\.papercut-repeat-options small\{font-weight:400\}/);
  assert.match(css, /\.papercut-shell>aside>\.papercut-repeat-options button\.active\{border-color:#171a20;background:#171a20;color:#fff/);
  assert.match(css, /\.papercut-preview-stage\.unfolded canvas\{cursor:grab\}/);
  assert.match(page, /<MuseumLoading \/>/);
  assert.match(page, /<DeferredMathGarden/);
  assert.match(page, /rootMargin: "240px 0px"/);
  assert.match(page, /body\.classList\.toggle\("garden-nav-theme", containsCenter\(garden\)\)/);
  assert.match(page, /body\.classList\.toggle\("workshop-nav-theme", containsCenter\(workshop\)\)/);
  assert.match(page, /bounds\.top <= viewportCenter && bounds\.bottom >= viewportCenter/);
  assert.match(page, /window\.addEventListener\("scroll", updateTheme/);
  assert.doesNotMatch(page, /entry\.intersectionRatio >= 0\.5/);
  assert.doesNotMatch(page, /updateNavigation|site-nav-visible/);
  assert.match(page, /certificateOpen \? "certificate-mode" : ""/);
  assert.match(garden, /classList\.toggle\("garden-detail-mode",Boolean\(selectedId\)\)/);
  assert.doesNotMatch(page, /GoldenFlower|FractalForest|GeometryBuilder|FourierSound|SpiralUniverse|journey-intro/);
  assert.match(layout, /Math Beauty Museum/);
  assert.match(layout, /viewportFit: "cover"/);
  assert.doesNotMatch(layout, /codex-preview|Starter Project/);
});

test("separates the heavy WebGL worlds from the compact page shell", async () => {
  const chunkDirectory = new URL("../dist/client/_next/static/chunks/", import.meta.url);
  const files = await readdir(chunkDirectory);
  const museumChunk = files.find((file) => file.startsWith("NatureMuseum3D-") && file.endsWith(".js"));
  const gardenChunk = files.find((file) => file.startsWith("MathGarden3D-") && file.endsWith(".js"));
  const workshopChunk = files.find((file) => file.startsWith("InteractiveWorkshop-") && file.endsWith(".js"));
  const pageChunk = files.find((file) => file.startsWith("page-") && file.endsWith(".js"));
  assert.ok(museumChunk, "the museum should be emitted as its own lazy chunk");
  assert.ok(gardenChunk, "the garden should be emitted as its own lazy chunk");
  assert.ok(workshopChunk, "the workshop should be emitted as its own lazy chunk");
  assert.ok(pageChunk, "the page entry chunk should exist");
  const pageSize = (await stat(new URL(pageChunk, chunkDirectory))).size;
  assert.ok(pageSize < 32 * 1024, `the initial page shell should stay below 32 KB; received ${pageSize} bytes`);
});
